# Generated by Django 3.0.4 on 2020-06-20 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200620_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='design_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='design',
            name='design_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 21, 34, 23, 186160), verbose_name='date published'),
        ),
    ]
