# Generated by Django 3.0.4 on 2020-06-20 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200620_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='design_content_image',
            field=models.ImageField(default='covers/df.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='design',
            name='design_cover',
            field=models.ImageField(default='covers/df.png', upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='design',
            name='design_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 0, 29, 28, 160756), verbose_name='date published'),
        ),
    ]
