# Generated by Django 3.0.4 on 2020-06-20 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200621_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='design_price',
            field=models.PositiveSmallIntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='design',
            name='design_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 0, 32, 45, 391411), verbose_name='date published'),
        ),
    ]
