# Generated by Django 3.0.4 on 2020-06-21 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200621_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='design_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 7, 33, 8, 601076), verbose_name='date published'),
        ),
    ]
