# Generated by Django 3.0.4 on 2020-06-21 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200621_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='design_likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='design',
            name='design_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 19, 34, 14, 336179), verbose_name='date published'),
        ),
    ]
