# Generated by Django 3.0.4 on 2020-06-21 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200621_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='design_content_image',
        ),
        migrations.AddField(
            model_name='design',
            name='design_content_image1',
            field=models.ImageField(default='', upload_to='images/', verbose_name='Snapshot 1'),
        ),
        migrations.AddField(
            model_name='design',
            name='design_content_image2',
            field=models.ImageField(default='', upload_to='images/', verbose_name='Snapshot 2'),
        ),
        migrations.AddField(
            model_name='design',
            name='design_content_image3',
            field=models.ImageField(default='', upload_to='images/', verbose_name='Snapshot 3'),
        ),
        migrations.AddField(
            model_name='design',
            name='design_content_image4',
            field=models.ImageField(default='', upload_to='images/', verbose_name='Snapshot 4'),
        ),
        migrations.AddField(
            model_name='design',
            name='design_content_image5',
            field=models.ImageField(default='', upload_to='images/', verbose_name='Snapshot 5'),
        ),
        migrations.AlterField(
            model_name='design',
            name='design_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 21, 35, 56, 993020), verbose_name='date published'),
        ),
    ]
