# Generated by Django 3.0.4 on 2020-06-21 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200621_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='design_content_image3',
            field=models.ImageField(blank=True, default='', upload_to='images/', verbose_name='Snapshot 3'),
        ),
        migrations.AlterField(
            model_name='design',
            name='design_content_image4',
            field=models.ImageField(blank=True, default='', upload_to='images/', verbose_name='Snapshot 4'),
        ),
        migrations.AlterField(
            model_name='design',
            name='design_content_image5',
            field=models.ImageField(blank=True, default='', upload_to='images/', verbose_name='Snapshot 5'),
        ),
        migrations.AlterField(
            model_name='design',
            name='design_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 21, 37, 13, 422665), verbose_name='date published'),
        ),
    ]
