# Generated by Django 3.0.4 on 2020-06-24 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200624_1848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MACKUser',
        ),
        migrations.AlterField(
            model_name='design',
            name='design_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 19, 25, 23, 757609), verbose_name='date published'),
        ),
    ]
