# Generated by Django 3.0.4 on 2020-08-29 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200829_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 29, 14, 30, 22, 136936), null=True, verbose_name='Date Of Paper'),
        ),
    ]
