# Generated by Django 3.0.4 on 2020-08-29 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200829_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='studnet',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 29, 14, 37, 0, 12995), null=True, verbose_name='Date Of Paper'),
        ),
    ]
