# Generated by Django 3.0.4 on 2020-08-30 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200830_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qid',
            field=models.CharField(default='9QY4S7WA', max_length=8, unique=True, verbose_name='Course ID'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 30, 16, 24, 23, 190795), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_cover',
            field=models.ImageField(blank=True, default='', upload_to='covers/', verbose_name='Cover Image'),
        ),
    ]
