# Generated by Django 3.0.4 on 2020-08-30 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200830_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ans_file10',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 10'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_file11',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 11'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_file12',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 12'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_file13',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 13'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_file14',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 14'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_file15',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 15'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_file16',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 16'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_file17',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 17'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_file18',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 18'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_file19',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 19'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_file2',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 2'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_file20',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 20'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_file21',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 21'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_file22',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 22'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_file23',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 23'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_file24',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 24'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_file3',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 3'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_file4',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 4'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_file5',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 5'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_file6',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 6'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_file7',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 7'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_file8',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 8'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_file9',
            field=models.FileField(blank=True, default='', upload_to='files/', verbose_name='Answer File 9'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_cover2',
            field=models.ImageField(blank=True, default='', upload_to='covers/', verbose_name='Cover Image 2'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_cover3',
            field=models.ImageField(blank=True, default='', upload_to='covers/', verbose_name='Cover Image 3'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_cover4',
            field=models.ImageField(blank=True, default='', upload_to='covers/', verbose_name='Cover Image 4'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_cover5',
            field=models.ImageField(blank=True, default='', upload_to='covers/', verbose_name='Cover Image 5'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_cover6',
            field=models.ImageField(blank=True, default='', upload_to='covers/', verbose_name='Cover Image 6'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_cover7',
            field=models.ImageField(blank=True, default='', upload_to='covers/', verbose_name='Cover Image 7'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_cover8',
            field=models.ImageField(blank=True, default='', upload_to='covers/', verbose_name='Cover Image 8'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 31, 0, 40, 42, 426027), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='OUU95C7O', max_length=8, unique=True, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_field',
            field=models.CharField(choices=[('other', 'OT - other'), ('computer science', 'CS - computer science'), ('math', 'MT - math'), ('physical science and engineering', 'PE - physical science and engineering'), ('arts and designing', 'AD - arts and designing'), ('social science', 'SS - social science'), ('health', 'HL - health'), ('data science', 'DS - data science'), ('language', 'LG - language'), ('business', 'BS - business')], default='other', max_length=200, verbose_name='Course Field'),
        ),
    ]
