# Generated by Django 3.0.4 on 2020-08-31 10:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20200831_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='File_name',
            field=models.CharField(default='', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 31, 16, 26, 25, 512053), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='QGU7X0EO', max_length=8, unique=True, verbose_name='Question ID'),
        ),
        migrations.CreateModel(
            name='BuyBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.EBook')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
            ],
        ),
    ]
