# Generated by Django 3.0.4 on 2020-08-31 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200831_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='Bcover',
            field=models.FileField(blank=True, default='', upload_to='ebook/', verbose_name='Book Cover'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 31, 16, 45, 24, 69090), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='63BJLNXY', max_length=8, unique=True, verbose_name='Question ID'),
        ),
    ]
