# Generated by Django 3.0.4 on 2020-08-31 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200831_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='Edition',
            field=models.CharField(default='1st Edition', max_length=200, verbose_name='Edition'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='price2',
            field=models.IntegerField(blank=True, default=0, verbose_name='Buy Price'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Rental Price'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 31, 23, 46, 28, 878427), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='ATZ0TUGG', max_length=8, unique=True, verbose_name='Question ID'),
        ),
    ]
