# Generated by Django 3.0.4 on 2020-09-01 08:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20200901_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 1, 14, 9, 9, 789196), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='LNXWTA13', max_length=8, unique=True, verbose_name='Question ID'),
        ),
    ]
