# Generated by Django 3.0.4 on 2020-09-01 08:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20200901_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksol',
            name='id',
        ),
        migrations.AlterField(
            model_name='booksol',
            name='Ebook',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.EBook'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 1, 14, 28, 26, 488767), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='O37Q23MA', max_length=8, unique=True, verbose_name='Question ID'),
        ),
    ]
