# Generated by Django 3.0.4 on 2020-09-02 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20200901_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 15, 1, 43, 628634), null=True, verbose_name='Date of Subscription'),
        ),
        migrations.AddField(
            model_name='student',
            name='subs',
            field=models.BooleanField(blank=True, default=False, verbose_name='Subscribed?'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 15, 1, 43, 638607), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='X5DOQXXO', max_length=8, unique=True, verbose_name='Question ID'),
        ),
    ]
