# Generated by Django 3.0.4 on 2020-09-02 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20200902_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='anual',
            field=models.BooleanField(blank=True, default=False, verbose_name='Yearly?'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 17, 44, 41, 497682), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='2H8RORGG', max_length=8, unique=True, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 17, 44, 41, 491700), null=True, verbose_name='Date of Subscription'),
        ),
    ]
