# Generated by Django 3.0.4 on 2020-09-02 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20200902_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Deadline',
        ),
        migrations.AddField(
            model_name='student',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 18, 6, 28, 663752), null=True, verbose_name='End Date of Subscription'),
        ),
        migrations.AddField(
            model_name='student',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 18, 6, 28, 662755), null=True, verbose_name='Start Date of Subscription'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 18, 6, 28, 672726), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='0BW5M5O4', max_length=8, unique=True, verbose_name='Question ID'),
        ),
    ]
