# Generated by Django 3.0.4 on 2020-09-02 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20200902_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='buybook',
            name='duration',
            field=models.BooleanField(blank=True, default=False, verbose_name='Permanent?'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 18, 29, 39, 809923), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='108VQDGX', max_length=8, unique=True, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 18, 29, 39, 798952), null=True, verbose_name='End Date of Subscription'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 18, 29, 39, 798952), null=True, verbose_name='Start Date of Subscription'),
        ),
    ]
