# Generated by Django 3.0.4 on 2020-09-02 15:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20200902_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktransaction',
            name='Book',
        ),
        migrations.RemoveField(
            model_name='booktransaction',
            name='made_by',
        ),
        migrations.AddField(
            model_name='booktransaction',
            name='book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.EBook'),
        ),
        migrations.AddField(
            model_name='booktransaction',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 21, 9, 7, 585420), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='02GEUNOK', max_length=8, unique=True, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 21, 9, 7, 580436), null=True, verbose_name='End Date of Subscription'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 21, 9, 7, 580436), null=True, verbose_name='Start Date of Subscription'),
        ),
    ]
