# Generated by Django 3.0.4 on 2020-09-02 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_auto_20200902_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktransaction',
            name='applied',
            field=models.BooleanField(blank=True, default=False, verbose_name='applied?'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 22, 53, 58, 47566), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='L0L729HT', max_length=8, unique=True, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 22, 53, 58, 40585), null=True, verbose_name='End Date of Subscription'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 22, 53, 58, 40585), null=True, verbose_name='Start Date of Subscription'),
        ),
    ]
