# Generated by Django 3.0.4 on 2020-09-05 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20200905_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='confirm',
            field=models.BooleanField(blank=True, default=False, verbose_name='Confirmed?'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 5, 13, 52, 0, 213464), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='12IKGEJH', max_length=8, unique=True, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 5, 13, 52, 0, 203493), null=True, verbose_name='End Date of Subscription'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 5, 13, 52, 0, 203493), null=True, verbose_name='Start Date of Subscription'),
        ),
    ]
