# Generated by Django 3.1.1 on 2020-09-11 11:41

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_auto_20200906_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='Email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Rental Price (Rs 450 min)'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='price2',
            field=models.IntegerField(blank=True, default=0, verbose_name='Buy Price (Rs 650 min)'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 11, 11, 41, 44, 41629), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='76GSJ6O8', max_length=8, unique=True, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=tinymce.models.HTMLField(verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='student',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 11, 11, 41, 44, 34024), null=True, verbose_name='End Date of Subscription'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 11, 11, 41, 44, 33988), null=True, verbose_name='Start Date of Subscription'),
        ),
    ]
