# Generated by Django 3.1.1 on 2020-09-11 11:44

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_auto_20200911_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=tinymce.models.HTMLField(default='', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='booksol',
            name='Description',
            field=tinymce.models.HTMLField(default='', verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='Description',
            field=tinymce.models.HTMLField(default='', verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='note',
            name='Description',
            field=tinymce.models.HTMLField(default='', verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 11, 11, 44, 51, 700088), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='2C2V69SU', max_length=8, unique=True, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 11, 11, 44, 51, 692843), null=True, verbose_name='End Date of Subscription'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 11, 11, 44, 51, 692804), null=True, verbose_name='Start Date of Subscription'),
        ),
    ]
