# Generated by Django 3.1.1 on 2020-09-22 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_auto_20200911_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='Uploaded',
            field=models.BooleanField(blank=True, default=False, verbose_name='Contributed Notes?'),
        ),
        migrations.AlterField(
            model_name='note',
            name='Email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='note',
            name='File',
            field=models.FileField(default='', upload_to='notes/', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 22, 4, 24, 20, 236116), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='FJQXGH30', max_length=8, unique=True, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 22, 4, 24, 20, 228046), null=True, verbose_name='End Date of Subscription'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 22, 4, 24, 20, 228006), null=True, verbose_name='Start Date of Subscription'),
        ),
    ]
