# Generated by Django 3.1.1 on 2020-09-22 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_auto_20200922_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='Uploaded',
            field=models.BooleanField(blank=True, default=False, verbose_name='Contributed Notes?'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 22, 4, 27, 19, 677322), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='E31BLK6H', max_length=8, unique=True, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 22, 4, 27, 19, 666540), null=True, verbose_name='End Date of Subscription'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 22, 4, 27, 19, 666502), null=True, verbose_name='Start Date of Subscription'),
        ),
    ]
