# Generated by Django 3.1.1 on 2020-09-26 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_auto_20200923_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Rental Price (USD 8 min)'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='price2',
            field=models.IntegerField(blank=True, default=0, verbose_name='Buy Price (USD 10 min)'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 26, 4, 50, 58, 878576), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='CNBJEUV9', max_length=8, unique=True, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 26, 4, 50, 58, 869293), null=True, verbose_name='End Date of Subscription'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 26, 4, 50, 58, 869256), null=True, verbose_name='Start Date of Subscription'),
        ),
    ]
