# Generated by Django 3.1.1 on 2020-09-27 11:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_auto_20200926_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 27, 11, 40, 18, 136526), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='30PI68ZS', max_length=8, unique=True, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 27, 11, 40, 18, 127155), null=True, verbose_name='End Date of Subscription'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 27, 11, 40, 18, 127115), null=True, verbose_name='Start Date of Subscription'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('ans', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.answer')),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
    ]
