# Generated by Django 3.1.1 on 2020-09-27 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_auto_20200927_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='Verify',
            field=models.BooleanField(default=True, verbose_name='Verified?'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='Uploaded',
            field=models.BooleanField(blank=True, default=False, verbose_name='Contributed Book?'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 27, 11, 45, 3, 111614), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='ZEZ26363', max_length=8, unique=True, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 27, 11, 45, 3, 100416), null=True, verbose_name='End Date of Subscription'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 27, 11, 45, 3, 100307), null=True, verbose_name='Start Date of Subscription'),
        ),
    ]
