# Generated by Django 3.1.1 on 2020-10-10 04:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0075_auto_20200927_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='buybook',
            name='rental',
            field=models.BooleanField(blank=True, default=False, verbose_name='Book rental?'),
        ),
        migrations.AddField(
            model_name='student',
            name='credits',
            field=models.IntegerField(blank=True, default=0, verbose_name='Credits Earned'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file10',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 10'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file11',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 11'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file12',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 12'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file13',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 13'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file14',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 14'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file15',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 15'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file16',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 16'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file17',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 17'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file18',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 18'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file19',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 19'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file2',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 2'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file20',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 20'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file21',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 21'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file22',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 22'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file23',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 23'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file24',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 24'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file3',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 3'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file4',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 4'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file5',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 5'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file6',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 6'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file7',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 7'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file8',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 8'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_file9',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='files/', verbose_name='Answer File 9'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='buybook',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 10, 4, 35, 40, 729308), null=True, verbose_name='End Date of Rental book'),
        ),
        migrations.AlterField(
            model_name='buybook',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 10, 4, 35, 40, 729282), null=True, verbose_name='Start Date Rental book'),
        ),
        migrations.AlterField(
            model_name='note',
            name='Uploaded',
            field=models.BooleanField(default=False, verbose_name='Contributed Notes?'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 10, 4, 35, 40, 728598), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='1QDJL3XW', max_length=8, unique=True, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 10, 4, 35, 40, 717839), null=True, verbose_name='End Date of Subscription'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 10, 4, 35, 40, 717797), null=True, verbose_name='Start Date of Subscription'),
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('credits', models.IntegerField()),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('checksum', models.CharField(blank=True, max_length=100, null=True)),
                ('applied', models.BooleanField(blank=True, default=False, verbose_name='applied?')),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
    ]
