# Generated by Django 3.1.1 on 2020-10-10 04:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0078_auto_20201010_0443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktransaction',
            old_name='made_on',
            new_name='madeon',
        ),
        migrations.RenameField(
            model_name='booktransaction',
            old_name='order_id',
            new_name='orderid',
        ),
        migrations.RenameField(
            model_name='credittransaction',
            old_name='made_on',
            new_name='madeon',
        ),
        migrations.RenameField(
            model_name='credittransaction',
            old_name='order_id',
            new_name='orderid',
        ),
        migrations.RenameField(
            model_name='substransaction',
            old_name='made_on',
            new_name='madeon',
        ),
        migrations.RenameField(
            model_name='substransaction',
            old_name='order_id',
            new_name='orderid',
        ),
        migrations.AlterField(
            model_name='buybook',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 10, 4, 59, 24, 545439), null=True, verbose_name='End Date of Rental book'),
        ),
        migrations.AlterField(
            model_name='buybook',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 10, 4, 59, 24, 545395), null=True, verbose_name='Start Date Rental book'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 10, 4, 59, 24, 544155), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='NEXTOA3E', max_length=8, unique=True, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 10, 4, 59, 24, 528220), null=True, verbose_name='End Date of Subscription'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 10, 4, 59, 24, 528172), null=True, verbose_name='Start Date of Subscription'),
        ),
       
    ]
