# Generated by Django 3.1.1 on 2020-10-12 04:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_auto_20201010_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktransaction',
            name='book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='main.ebook'),
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='main.student'),
        ),
        migrations.AlterField(
            model_name='buybook',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 12, 4, 46, 27, 190818), null=True, verbose_name='End Date of Rental book'),
        ),
        migrations.AlterField(
            model_name='buybook',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 12, 4, 46, 27, 190792), null=True, verbose_name='Start Date Rental book'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='main.student'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 12, 4, 46, 27, 190180), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='EQCLMD6Y', max_length=8, unique=True, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 12, 4, 46, 27, 180942), null=True, verbose_name='End Date of Subscription'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 12, 4, 46, 27, 180904), null=True, verbose_name='Start Date of Subscription'),
        ),
        migrations.AlterField(
            model_name='substransaction',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='main.student'),
        ),
        migrations.CreateModel(
            name='Refer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referedby', models.CharField(default='', max_length=200, verbose_name='Student ID')),
                ('madeon', models.DateTimeField(auto_now_add=True)),
                ('credits', models.IntegerField()),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='main.student')),
            ],
        ),
    ]
