# Generated by Django 3.1.1 on 2020-10-22 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_auto_20201022_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fieldofexpertise',
            field=models.CharField(choices=[('other', 'OT - other'), ('computer science', 'CS - computer science'), ('math', 'MT - math'), ('physical science and engineering', 'PE - physical science and engineering'), ('arts and designing', 'AD - arts and designing'), ('social science', 'SS - social science'), ('health', 'HL - health'), ('data science', 'DS - data science'), ('language', 'LG - language'), ('business', 'BS - business')], default='other', max_length=200, verbose_name='Field of expertise'),
        ),
        migrations.AddField(
            model_name='student',
            name='testscore',
            field=models.IntegerField(blank=True, default=0, verbose_name='Test Score / 100'),
        ),
        migrations.AlterField(
            model_name='buybook',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 22, 11, 0, 20, 782937), null=True, verbose_name='End Date of Rental book'),
        ),
        migrations.AlterField(
            model_name='buybook',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 22, 11, 0, 20, 782907), null=True, verbose_name='Start Date Rental book'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 22, 11, 0, 20, 782299), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='VCXKZDHZ', max_length=8, unique=True, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 22, 11, 0, 20, 772226), null=True, verbose_name='End Date of Subscription'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 22, 11, 0, 20, 772188), null=True, verbose_name='Start Date of Subscription'),
        ),
    ]
