# Generated by Django 3.1.1 on 2020-10-22 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_auto_20201022_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buybook',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 22, 12, 37, 19, 959250), null=True, verbose_name='End Date of Rental book'),
        ),
        migrations.AlterField(
            model_name='buybook',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 22, 12, 37, 19, 959223), null=True, verbose_name='Start Date Rental book'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 22, 12, 37, 19, 958645), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='P1U858IO', max_length=8, unique=True, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='quizequestion',
            name='question_field',
            field=models.CharField(choices=[('chemistry', 'CHEM - chemistry'), ('computer science', 'CS - computer science'), ('math', 'MT - math'), ('physics', 'PHY - Physics'), ('economics', 'ECON - Economics')], default='math', max_length=200, verbose_name='Question Field'),
        ),
        migrations.AlterField(
            model_name='student',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 22, 12, 37, 19, 949536), null=True, verbose_name='End Date of Subscription'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 22, 12, 37, 19, 949499), null=True, verbose_name='Start Date of Subscription'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fieldofexpertise',
            field=models.CharField(blank=True, max_length=255, verbose_name='Field of expertise'),
        ),
    ]
