# Generated by Django 3.1.1 on 2020-10-24 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_auto_20201024_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answer_cover',
            field=models.ImageField(blank=True, default='', max_length=255, upload_to='quizquestion_choice/', verbose_name='Answer Image'),
        ),
        migrations.AlterField(
            model_name='buybook',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 24, 14, 0, 51, 489488), null=True, verbose_name='End Date of Rental book'),
        ),
        migrations.AlterField(
            model_name='buybook',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 24, 14, 0, 51, 489444), null=True, verbose_name='Start Date Rental book'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 24, 14, 0, 51, 488387), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='078YRRNJ', max_length=8, unique=True, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 24, 14, 0, 51, 466143), null=True, verbose_name='End Date of Subscription'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 24, 14, 0, 51, 466039), null=True, verbose_name='Start Date of Subscription'),
        ),
    ]
