# Generated by Django 3.1.1 on 2020-12-08 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_auto_20201111_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='playlist',
            field=models.URLField(default='https://open.spotify.com/embed/playlist/0EEokYI5NzQa0Wfw5BieuS'),
        ),
        migrations.AlterField(
            model_name='buybook',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 8, 4, 54, 46, 590546), null=True, verbose_name='End Date of Rental book'),
        ),
        migrations.AlterField(
            model_name='buybook',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 8, 4, 54, 46, 590519), null=True, verbose_name='Start Date Rental book'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 8, 4, 54, 46, 589912), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='0S2REIVL', max_length=8, unique=True, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='refer',
            name='referedby',
            field=models.CharField(default='', max_length=200, verbose_name='Refer ID'),
        ),
        migrations.AlterField(
            model_name='searche',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 8, 4, 54, 46, 583408), null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 8, 4, 54, 46, 579409), null=True, verbose_name='End Date of Subscription'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 8, 4, 54, 46, 579373), null=True, verbose_name='Start Date of Subscription'),
        ),
    ]
