# Generated by Django 3.1.1 on 2020-12-12 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_auto_20201212_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='student',
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.CharField(blank=True, default='', max_length=700, verbose_name='User'),
        ),
        
        migrations.AlterField(
            model_name='buybook',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 12, 8, 19, 10, 744830), null=True, verbose_name='End Date of Rental book'),
        ),
        migrations.AlterField(
            model_name='buybook',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 12, 8, 19, 10, 744804), null=True, verbose_name='Start Date Rental book'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='concern',
            field=models.CharField(default='', max_length=2000, verbose_name='how?'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 12, 8, 19, 10, 744234), null=True, verbose_name='Date Of Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='DFHV25P0', max_length=8, unique=True, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='searche',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 12, 8, 19, 10, 737388), null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 12, 8, 19, 10, 733312), null=True, verbose_name='End Date of Subscription'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 12, 8, 19, 10, 733276), null=True, verbose_name='Start Date of Subscription'),
        ),
    ]
